### ISSUE TITLE
CLI Broken in 2.0.1

### ISSUE THREAD

**Issue by MartinRamm** [mryogesh/google-playstore-publisher#3]
The CLI seems to be broken in the last release. Google returns a 400.

I did some debugging (unfortunately the output doesn't contain the response body) and the body of the error response is this:
```
{
  error: {
    code: 400,
    message: 'Invalid package name: undefined.',
    status: 'INVALID_ARGUMENT'
  }
}
```

Some further digging shows that the variable [packageName that is used here](https://github.com/mryogesh/google-playstore-publisher/blob/2.0.1/cli.js#L53) is not parsed by `yargs`.

**Comment by mryogesh** [comment]
Hi @MartinRamm 

Thanks for reporting. Fixed it.
